# Generated by Django 2.2.17 on 2021-05-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='head_coach',
            field=models.CharField(default=1, max_length=70, verbose_name='Главный тренер команды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='tag_href',
            field=models.CharField(default=1, max_length=70, verbose_name='Ccылка на страницу профиля команды'),
            preserve_default=False,
        ),
    ]
